---
name: test-network-org1
version: "2.0.0"
caliper:
  blockchain: fabric
channels:
  - channelName: channelb
    contracts:
      - id: channelb_ledger

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk'
          clientSignedCert:
            path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem'
    connectionProfile:
      path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org1.example.com/connection-org1.yaml'
      discover: true
  - mspid: Org2MSP
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/priv_sk'
          clientSignedCert:
            path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/User1@org2.example.com-cert.pem'
    connectionProfile:
      path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org2.example.com/connection-org2.yaml'
      discover: true
  - mspid: Org3MSP
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/keystore/priv_sk'
          clientSignedCert:
            path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/signcerts/User1@org3.example.com-cert.pem'
    connectionProfile:
      path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org3.example.com/connection-org3.yaml'
      discover: true