---
name: test-network-org1
version: "2.0.0"
caliper:
  blockchain: fabric
channels:
  - channelName: channelc
    contracts:
      - id: channelc_ledger
organizations:
  - mspid: Org4MSP
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/keystore/priv_sk'
          clientSignedCert:
            path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/signcerts/User1@org4.example.com-cert.pem'
    connectionProfile:
      path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org4.example.com/connection-org4.yaml'
      discover: true
  - mspid: Org5MSP
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org5.example.com/users/User1@org5.example.com/msp/keystore/priv_sk'
          clientSignedCert:
            path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org5.example.com/users/User1@org5.example.com/msp/signcerts/User1@org5.example.com-cert.pem'
    connectionProfile:
      path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org5.example.com/connection-org5.yaml'
      discover: true
  - mspid: Org6MSP
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org6.example.com/users/User1@org6.example.com/msp/keystore/priv_sk'
          clientSignedCert:
            path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org6.example.com/users/User1@org6.example.com/msp/signcerts/User1@org6.example.com-cert.pem'
    connectionProfile:
      path: '/etc/hyperledger/fabric/crypto-config/peerOrganizations/org6.example.com/connection-org6.yaml'
      discover: true
