test:
  name: ChannelB Vehicle Status Test
  description: Test for vehicle status on ChannelB smart contract

  workers:
    number: 5 # 并发线程数

  rounds:
    - label: CreateVehicleStatus
      txNumber: 100 # 总交易数量
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5 # 每秒发送交易数
      workload:
        module: workload/createVehicleStatus.js # 指向工作负载文件的位置
    - label: Query VehicleStatus
      txNumber: 100 # 总交易数量
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: workload/queryVehicleStatus.js
        arguments:
          assets: 100
    - label: Update VehicleStatus
      txNumber: 100 # 总交易数量
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: workload/updateVehicleStatus.js
        arguments:
          assets: 100
    - label: Delete VehicleStatus
      txNumber: 100 # 总交易数量
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: workload/deleteVehicleStatus.js
        arguments:
          assets: 100
